DevOps: Implement Invalidate CloudFront cache and wait for completion step

diff --git a/.github/workflows/deploy_docs_to_s3.yml b/.github/workflows/deploy_docs_to_s3.yml
--- a/.github/workflows/deploy_docs_to_s3.yml
+++ b/.github/workflows/deploy_docs_to_s3.yml
@@ -42,19 +42,38 @@ jobs:
     - name: Generate Doxygen documentation
       run: doxygen Doxyfile
 
-    - name: Use variables
-      run: |
-        echo "AWS_REGION: '${{ vars.AWS_REGION }}'"
-        echo "AWS_REGION no vars context: '$AWS_REGION'"
-        echo "AWS_REGION env context: '${{ env.AWS_REGION }}'"
-
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
-        aws-region: us-east-1
+        aws-region: '${{ vars.AWS_REGION }}'
         audience: sts.amazonaws.com
         role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
 
     - name: Sync S3 bucket
       run: |
         aws s3 sync ./documentation/html s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
+
+    - name: Invalidate CloudFront cache and wait for completion
+      env:
+        DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
+      run: |
+        INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --query 'Invalidation.Id' --output text)
+        echo "Created invalidation with ID: $INVALIDATION_ID"
+        STATUS="InProgress"
+        TIMEOUT=120  # 2 minutes timeout
+        START_TIME=$(date +%s)
+
+        while [ "$STATUS" == "InProgress" ]; do
+          CURRENT_TIME=$(date +%s)
+          ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+
+          if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
+            echo "Invalidation timeout after $ELAPSED_TIME seconds"
+            exit 1
+          fi
+
+          STATUS=$(aws cloudfront get-invalidation --distribution-id $DISTRIBUTION_ID --id $INVALIDATION_ID --query 'Invalidation.Status' --output text)
+          echo "Invalidation status: $STATUS"
+          [ "$STATUS" == "InProgress" ] && sleep 20
+        done
+        echo "Invalidation completed with status: $STATUS"
